"""Generate board-side credential files from ``~/.dusty/``.

A microcontroller cannot read ``~/.dusty/``, so the files it *can* read are
produced from it at deploy time:

* ``secrets.py``        — MicroPython module, copied to board flash
* ``sdkconfig.secrets`` — ESP-IDF fragment, compiled into firmware

Both are gitignored at their destinations. Regenerate rather than hand-edit:
``~/.dusty/secrets.toml`` is the source of truth.
"""

from __future__ import annotations

import os
import stat
from pathlib import Path

from .config import ConfigError, Section, load

#: TOML path -> the flat UPPER_CASE name the on-device code imports.
#: Board code does ``import secrets; secrets.WIFI_SSID``, so these names are
#: an interface — renaming one means editing firmware.
SHARED_KEYS = {
    ("wifi", "ssid"): "WIFI_SSID",
    ("wifi", "password"): "WIFI_PASS",
    ("server", "host"): "SERVER_HOST",
    ("server", "port"): "SERVER_PORT",
    ("mqtt", "user"): "MQTT_USER",
    ("mqtt", "password"): "MQTT_PASS",
    ("mqtt", "topic"): "MQTT_TOPIC",
    ("webrepl", "password"): "WEBREPL_PASS",
}

HEADER = (
    "# GENERATED by `dusty generate` from ~/.dusty/ — do not edit.\n"
    "# Source of truth: ~/.dusty/config.toml + ~/.dusty/secrets.toml\n"
)


def flatten(cfg: Section, sections: tuple[str, ...]) -> dict:
    """Flatten a camera-scoped config into the board's UPPER_CASE namespace.

    Only the shared sections a camera actually declares are included — the
    ESP32 board has no MQTT client, so it should never receive the MQTT
    password. Everything in the camera's own section passes through
    upper-cased, so adding a knob to ``[camera.x]`` needs no change here.
    """
    out: dict[str, object] = {}
    for (section, key), name in SHARED_KEYS.items():
        if section not in sections:
            continue
        if section in cfg and key in cfg[section]:
            out[name] = cfg[section][key]
    for key, value in cfg.get("camera", {}).items():
        if isinstance(value, (str, int, float, bool)):
            out[key.upper()] = value
    return out


def board_secrets(cfg: Section, sections: tuple[str, ...]) -> str:
    """Render a MicroPython ``secrets.py``."""
    lines = [HEADER]
    name = cfg.get("camera_name")
    if name:
        lines.append(f"# camera: {name}\n")
    lines.append("\n")
    for key, value in sorted(flatten(cfg, sections).items()):
        lines.append(f"{key} = {value!r}\n")
    return "".join(lines)


def sdkconfig_secrets(cfg: Section, sections: tuple[str, ...]) -> str:
    """Render an ESP-IDF ``sdkconfig.secrets`` fragment."""
    flat = flatten(cfg, sections)
    lines = [HEADER]
    for key in ("WIFI_SSID", "WIFI_PASS", "SERVER_HOST", "SERVER_PORT"):
        if key not in flat:
            continue
        value = flat[key]
        rendered = str(value) if isinstance(value, int) and not isinstance(value, bool) else f'"{value}"'
        lines.append(f"CONFIG_SAMPLE_{key}={rendered}\n")
    return "".join(lines)


def write_private(path: Path, text: str) -> Path:
    """Write ``text`` to ``path`` with mode 0600, creating parents."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)
    return path


#: Per camera: which shared secret sections it may receive, and what to write.
#: ``sections`` is a least-privilege allowlist — a board only gets credentials
#: for services it actually talks to. Destinations are gitignored.
TARGETS = {
    "esp32_s3_cam": {
        "sections": ("wifi", "server", "webrepl"),
        "files": [
            ("cameras/esp32_s3_cam/software/src/secrets.py", board_secrets),
            ("cameras/esp32_s3_cam/software/persondet_app/sdkconfig.secrets", sdkconfig_secrets),
        ],
    },
    "openmv_n6": {
        "sections": ("wifi", "server", "mqtt"),
        "files": [
            ("cameras/openmv_n6/software/secrets.py", board_secrets),
        ],
    },
}


def generate(camera: str, repo_root: Path) -> list[Path]:
    """Write every generated credential file for one camera. Returns paths."""
    if camera not in TARGETS:
        raise ConfigError(
            f"unknown camera {camera!r} (have: {', '.join(sorted(TARGETS))})"
        )
    target = TARGETS[camera]
    cfg = load(camera=camera)
    return [
        write_private(repo_root / rel, render(cfg, target["sections"]))
        for rel, render in target["files"]
    ]
