# main.py — wavecam continuous audio streamer
# Captures 8 kHz mono from the ES7210 mics and POSTs 5 s PCM chunks to the
# pump server on homegpu (:8090). Ring buffer rides out Wi-Fi/server hiccups.
# Timeline UI lives on the server: http://192.168.86.26:8090/
import gc
import time
import network
import ubinascii
import machine
from machine import Pin, I2C, I2S, PWM
import requests

# Credentials live in secrets.py (deployed to the board, never committed) —
# same convention as src/uplink.py. Generated by `dusty generate esp32_s3_cam`.
try:
    import secrets
except ImportError:
    secrets = None

WIFI_SSID = secrets.WIFI_SSID if secrets else None
WIFI_PASS = secrets.WIFI_PASS if secrets else None

SERVER = "http://192.168.86.26:8090/ingest?boot=%s&seq=%d"
RATE = 8000            # mono 8k on the wire (80KB/chunk) — thin-backhaul friendly
CHUNK_SEC = 5
CHUNK_BYTES = RATE * 2 * CHUNK_SEC
RING_MAX = 40          # ~3.3 min of backlog in PSRAM (80KB/chunk)
BOOT_ID = ubinascii.hexlify(machine.unique_id()).decode() + "-%d" % (time.ticks_ms() & 0xFFFF)

i2c = I2C(1, sda=Pin(8), scl=Pin(7), freq=100000)
ES = 0x40


def _wr(reg, val):
    i2c.writeto_mem(ES, reg, bytes([val]))


def _rd(reg):
    return i2c.readfrom_mem(ES, reg, 1)[0]


def _upd(reg, mask, val):
    _wr(reg, (_rd(reg) & (0xFF ^ mask)) | (val & mask))


def es7210_init(gain=12):  # 12 = 34.5 dB PGA
    _wr(0x00, 0xFF)
    _wr(0x00, 0x41)
    _wr(0x01, 0x3F)
    _wr(0x09, 0x30)
    _wr(0x0A, 0x30)
    _wr(0x23, 0x2A)
    _wr(0x22, 0x0A)
    _wr(0x20, 0x0A)
    _wr(0x21, 0x2A)
    _upd(0x08, 0x01, 0x00)          # I2S slave
    _wr(0x40, 0x43)
    _wr(0x41, 0x70)
    _wr(0x42, 0x70)
    # 8 kHz, MCLK = 2.048 MHz (256*fs) — the mono combo that tested live
    _wr(0x07, 0x20)
    _wr(0x02, 0x41)
    _wr(0x04, 0x02)
    _wr(0x05, 0x00)
    _wr(0x11, (_rd(0x11) & 0x1F) | 0x60)   # 16-bit
    _wr(0x11, _rd(0x11) & 0xFC)            # I2S normal
    for i in range(4):
        _upd(0x43 + i, 0x10, 0x00)
    _wr(0x4B, 0xFF)
    _wr(0x4C, 0xFF)
    for greg in (0x43, 0x44):
        _upd(0x01, 0x0B, 0x00)
        _wr(0x4B, 0x00)
        _upd(greg, 0x10, 0x10)
        _upd(greg, 0x0F, gain)
    _wr(0x12, 0x00)
    _wr(0x06, 0x00)
    _wr(0x40, 0x43)
    for preg in (0x47, 0x48, 0x49, 0x4A):
        _wr(preg, 0x08)


def self_update():
    """Fetch staged firmware from the server, syntax-verify, install, reboot.
    Triggered by HTTP 210 on /ingest — the reliable OTA path (WebREPL is
    starved by this loop and can't be used while streaming)."""
    import os
    try:
        r = requests.get("http://192.168.86.26:8090/fw", timeout=20)
        data = r.content.decode()
        r.close()
        if len(data) < 1000:
            raise ValueError("too small (%d)" % len(data))
        compile(data, "main.py", "exec")   # reject truncated/corrupt download
        with open("main_new.py", "w") as f:
            f.write(data)
        os.rename("main_new.py", "main.py")
        print("firmware updated (%d bytes), rebooting" % len(data))
        time.sleep(1)
        machine.reset()
    except Exception as e:
        print("self-update failed:", e)


def main():
    wdt = machine.WDT(timeout=120000)      # hangs get 2 min, then hard reset
    mclk = PWM(Pin(10), freq=RATE * 256)   # 4.096 MHz
    mclk.duty_u16(32768)
    es7210_init()
    audio = I2S(0, sck=Pin(11), ws=Pin(12), sd=Pin(13),
                mode=I2S.RX, bits=16, format=I2S.MONO, rate=RATE,
                ibuf=480000)               # ~30 s cushion (PSRAM) so retry
                                           # stalls never overflow capture
    chunk = bytearray(CHUNK_BYTES)
    junk = bytearray(3200)
    audio.readinto(junk)                   # discard codec settling
    sta = network.WLAN(network.STA_IF)
    scan_note = [""]
    if sta.isconnected():
        try:
            scan_note[0] = "connected rssi %ddBm" % sta.status("rssi")
        except OSError:
            pass
    ring = []
    seq = 0
    fails = 0
    print("streaming as boot", BOOT_ID)
    while True:
        wdt.feed()
        audio.readinto(chunk)
        ring.append((seq, bytes(chunk)))
        seq += 1
        if len(ring) > RING_MAX:
            ring.pop(0)
        if not sta.isconnected() and fails % 12 == 6:   # retry wifi every ~60s
            print("wifi down, rescanning for best AP")
            try:
                sta.disconnect()
            except OSError:
                pass
            best = None
            try:
                cands = [a for a in sta.scan() if a[0] == WIFI_SSID.encode()]
                if cands:
                    ap = max(cands, key=lambda a: a[3])
                    best = ap[1]
                    scan_note[0] = ",".join(
                        "%s ch%d %ddBm" % (a[1].hex()[-4:], a[2], a[3])
                        for a in sorted(cands, key=lambda a: -a[3]))
                    print("APs seen:", scan_note[0])
            except OSError:
                pass
            if best:
                sta.connect(WIFI_SSID, WIFI_PASS, bssid=best)
            else:
                sta.connect(WIFI_SSID, WIFI_PASS)
        sent = 0
        while ring and sent < 3:           # bounded so capture never starves
            s, data = ring[0]
            try:
                r = requests.post(SERVER % (BOOT_ID, s), data=data, timeout=4)
                code = r.status_code
                r.close()
                if code in (200, 210):
                    ring.pop(0)
                    sent += 1
                    fails = 0
                    if code == 210:        # server has new firmware staged
                        self_update()
                    if scan_note[0]:
                        try:
                            rssi = sta.status("rssi")
                            r2 = requests.post(
                                "http://192.168.86.26:8090/scan",
                                data="boot=%s now_rssi=%d seen: %s"
                                % (BOOT_ID, rssi, scan_note[0]), timeout=3)
                            r2.close()
                            scan_note[0] = ""
                        except Exception:
                            pass
                elif code == 418:
                    print("server ordered reset")
                    time.sleep(1)
                    machine.reset()
                else:
                    print("server said", code)
                    break
            except Exception as e:
                fails += 1
                gc.collect()               # reclaim any socket leaked mid-post
                if fails % 12 == 1:
                    print("post failed (%d): %s, backlog %d" % (fails, e, len(ring)))
                break
        if fails >= 100:                   # ~8 min unreachable: clean slate
            print("unreachable too long, rebooting")
            time.sleep(1)
            machine.reset()
        if seq % 60 == 0:
            print("seq %d, backlog %d" % (seq, len(ring)))


try:
    main()
except Exception as e:
    print("fatal:", e)
    time.sleep(5)
    machine.reset()                        # never die to the REPL in the field
